
################################################################################
## Form generated from reading UI file 'scan.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import QCoreApplication, QMetaObject, QRect, QSize, Qt
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import QComboBox, QFrame, QLabel, QLineEdit, QPushButton, QSizePolicy


class Ui_scan:
    def setupUi(self, scan):
        if not scan.objectName():
            scan.setObjectName("scan")
        scan.resize(1180, 535)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(scan.sizePolicy().hasHeightForWidth())
        scan.setSizePolicy(sizePolicy)
        scan.setMinimumSize(QSize(1180, 535))
        scan.setMaximumSize(QSize(1180, 535))
        scan.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_area = QFrame(scan)
        self.arti_area.setObjectName("arti_area")
        self.arti_area.setGeometry(QRect(5, 35, 210, 495))
        sizePolicy.setHeightForWidth(self.arti_area.sizePolicy().hasHeightForWidth())
        self.arti_area.setSizePolicy(sizePolicy)
        self.arti_area.setMinimumSize(QSize(210, 495))
        self.arti_area.setMaximumSize(QSize(210, 495))
        self.arti_area.setStyleSheet("#arti_area  {border-top-left-radius: 5px; border-bottom-left-radius: 5px; border-bottom-right-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_area.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_area.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_type_area = QFrame(self.arti_area)
        self.arti_type_area.setObjectName("arti_type_area")
        self.arti_type_area.setGeometry(QRect(0, 300, 210, 35))
        sizePolicy.setHeightForWidth(self.arti_type_area.sizePolicy().hasHeightForWidth())
        self.arti_type_area.setSizePolicy(sizePolicy)
        self.arti_type_area.setMinimumSize(QSize(210, 35))
        self.arti_type_area.setMaximumSize(QSize(210, 35))
        self.arti_type_area.setStyleSheet("#arti_type_area {background-color: rgba(128, 128, 128, 64);}")
        self.arti_type_area.setFrameShape(QFrame.Shape.NoFrame)
        self.arti_type_area.setFrameShadow(QFrame.Shadow.Plain)
        self.arti_type_area.setLineWidth(0)
        self.arti_type_name = QLabel(self.arti_type_area)
        self.arti_type_name.setObjectName("arti_type_name")
        self.arti_type_name.setGeometry(QRect(5, 5, 200, 25))
        sizePolicy.setHeightForWidth(self.arti_type_name.sizePolicy().hasHeightForWidth())
        self.arti_type_name.setSizePolicy(sizePolicy)
        self.arti_type_name.setMinimumSize(QSize(200, 25))
        self.arti_type_name.setMaximumSize(QSize(200, 25))
        self.arti_type_name.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_name_d = QComboBox(self.arti_area)
        self.arti_name_d.setObjectName("arti_name_d")
        self.arti_name_d.setGeometry(QRect(5, 465, 145, 25))
        sizePolicy.setHeightForWidth(self.arti_name_d.sizePolicy().hasHeightForWidth())
        self.arti_name_d.setSizePolicy(sizePolicy)
        self.arti_name_d.setMinimumSize(QSize(145, 25))
        self.arti_name_d.setMaximumSize(QSize(145, 25))
        self.arti_name_d.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_name_c = QComboBox(self.arti_area)
        self.arti_name_c.setObjectName("arti_name_c")
        self.arti_name_c.setGeometry(QRect(5, 435, 145, 25))
        sizePolicy.setHeightForWidth(self.arti_name_c.sizePolicy().hasHeightForWidth())
        self.arti_name_c.setSizePolicy(sizePolicy)
        self.arti_name_c.setMinimumSize(QSize(145, 25))
        self.arti_name_c.setMaximumSize(QSize(145, 25))
        self.arti_name_c.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_b = QLineEdit(self.arti_area)
        self.arti_data_b.setObjectName("arti_data_b")
        self.arti_data_b.setGeometry(QRect(155, 405, 50, 25))
        sizePolicy.setHeightForWidth(self.arti_data_b.sizePolicy().hasHeightForWidth())
        self.arti_data_b.setSizePolicy(sizePolicy)
        self.arti_data_b.setMinimumSize(QSize(50, 25))
        self.arti_data_b.setMaximumSize(QSize(50, 25))
        self.arti_data_b.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_b.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.arti_data_b.setReadOnly(False)
        self.arti_data_a = QLineEdit(self.arti_area)
        self.arti_data_a.setObjectName("arti_data_a")
        self.arti_data_a.setGeometry(QRect(155, 375, 50, 25))
        sizePolicy.setHeightForWidth(self.arti_data_a.sizePolicy().hasHeightForWidth())
        self.arti_data_a.setSizePolicy(sizePolicy)
        self.arti_data_a.setMinimumSize(QSize(50, 25))
        self.arti_data_a.setMaximumSize(QSize(50, 25))
        self.arti_data_a.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_a.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.arti_data_a.setReadOnly(False)
        self.arti_name_a = QComboBox(self.arti_area)
        self.arti_name_a.setObjectName("arti_name_a")
        self.arti_name_a.setGeometry(QRect(5, 375, 145, 25))
        sizePolicy.setHeightForWidth(self.arti_name_a.sizePolicy().hasHeightForWidth())
        self.arti_name_a.setSizePolicy(sizePolicy)
        self.arti_name_a.setMinimumSize(QSize(145, 25))
        self.arti_name_a.setMaximumSize(QSize(145, 25))
        self.arti_name_a.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_c = QLineEdit(self.arti_area)
        self.arti_data_c.setObjectName("arti_data_c")
        self.arti_data_c.setGeometry(QRect(155, 435, 50, 25))
        sizePolicy.setHeightForWidth(self.arti_data_c.sizePolicy().hasHeightForWidth())
        self.arti_data_c.setSizePolicy(sizePolicy)
        self.arti_data_c.setMinimumSize(QSize(50, 25))
        self.arti_data_c.setMaximumSize(QSize(50, 25))
        self.arti_data_c.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_c.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.arti_data_c.setReadOnly(False)
        self.arti_main = QFrame(self.arti_area)
        self.arti_main.setObjectName("arti_main")
        self.arti_main.setGeometry(QRect(0, 335, 210, 35))
        sizePolicy.setHeightForWidth(self.arti_main.sizePolicy().hasHeightForWidth())
        self.arti_main.setSizePolicy(sizePolicy)
        self.arti_main.setMinimumSize(QSize(210, 35))
        self.arti_main.setMaximumSize(QSize(210, 35))
        self.arti_main.setStyleSheet("#arti_main {background-color: rgba(96, 96, 96, 128);}")
        self.arti_main.setFrameShape(QFrame.Shape.NoFrame)
        self.arti_main.setFrameShadow(QFrame.Shadow.Plain)
        self.arti_main.setLineWidth(0)
        self.arti_name_main = QComboBox(self.arti_main)
        self.arti_name_main.setObjectName("arti_name_main")
        self.arti_name_main.setGeometry(QRect(5, 5, 145, 25))
        sizePolicy.setHeightForWidth(self.arti_name_main.sizePolicy().hasHeightForWidth())
        self.arti_name_main.setSizePolicy(sizePolicy)
        self.arti_name_main.setMinimumSize(QSize(145, 25))
        self.arti_name_main.setMaximumSize(QSize(145, 25))
        self.arti_name_main.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_main = QLineEdit(self.arti_main)
        self.arti_data_main.setObjectName("arti_data_main")
        self.arti_data_main.setGeometry(QRect(155, 5, 50, 25))
        sizePolicy.setHeightForWidth(self.arti_data_main.sizePolicy().hasHeightForWidth())
        self.arti_data_main.setSizePolicy(sizePolicy)
        self.arti_data_main.setMinimumSize(QSize(50, 25))
        self.arti_data_main.setMaximumSize(QSize(50, 25))
        self.arti_data_main.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_main.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.arti_data_main.setReadOnly(True)
        self.arti_data_d = QLineEdit(self.arti_area)
        self.arti_data_d.setObjectName("arti_data_d")
        self.arti_data_d.setGeometry(QRect(155, 465, 50, 25))
        sizePolicy.setHeightForWidth(self.arti_data_d.sizePolicy().hasHeightForWidth())
        self.arti_data_d.setSizePolicy(sizePolicy)
        self.arti_data_d.setMinimumSize(QSize(50, 25))
        self.arti_data_d.setMaximumSize(QSize(50, 25))
        self.arti_data_d.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_data_d.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.arti_data_d.setReadOnly(False)
        self.arti_name_b = QComboBox(self.arti_area)
        self.arti_name_b.setObjectName("arti_name_b")
        self.arti_name_b.setGeometry(QRect(5, 405, 145, 25))
        sizePolicy.setHeightForWidth(self.arti_name_b.sizePolicy().hasHeightForWidth())
        self.arti_name_b.setSizePolicy(sizePolicy)
        self.arti_name_b.setMinimumSize(QSize(145, 25))
        self.arti_name_b.setMaximumSize(QSize(145, 25))
        self.arti_name_b.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_type = QComboBox(self.arti_area)
        self.arti_type.setObjectName("arti_type")
        self.arti_type.setGeometry(QRect(5, 240, 200, 25))
        sizePolicy.setHeightForWidth(self.arti_type.sizePolicy().hasHeightForWidth())
        self.arti_type.setSizePolicy(sizePolicy)
        self.arti_type.setMinimumSize(QSize(200, 25))
        self.arti_type.setMaximumSize(QSize(200, 25))
        self.arti_type.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_levl = QComboBox(self.arti_area)
        self.arti_levl.setObjectName("arti_levl")
        self.arti_levl.setGeometry(QRect(5, 270, 95, 25))
        sizePolicy.setHeightForWidth(self.arti_levl.sizePolicy().hasHeightForWidth())
        self.arti_levl.setSizePolicy(sizePolicy)
        self.arti_levl.setMinimumSize(QSize(95, 25))
        self.arti_levl.setMaximumSize(QSize(95, 25))
        self.arti_levl.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_rare = QComboBox(self.arti_area)
        self.arti_rare.setObjectName("arti_rare")
        self.arti_rare.setGeometry(QRect(110, 270, 95, 25))
        sizePolicy.setHeightForWidth(self.arti_rare.sizePolicy().hasHeightForWidth())
        self.arti_rare.setSizePolicy(sizePolicy)
        self.arti_rare.setMinimumSize(QSize(95, 25))
        self.arti_rare.setMaximumSize(QSize(95, 25))
        self.arti_rare.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_head_area = QLabel(self.arti_area)
        self.arti_head_area.setObjectName("arti_head_area")
        self.arti_head_area.setGeometry(QRect(5, 35, 200, 200))
        sizePolicy.setHeightForWidth(self.arti_head_area.sizePolicy().hasHeightForWidth())
        self.arti_head_area.setSizePolicy(sizePolicy)
        self.arti_head_area.setMinimumSize(QSize(200, 200))
        self.arti_head_area.setMaximumSize(QSize(200, 200))
        self.arti_head_area.setStyleSheet("")
        self.arti_head_area.setPixmap(QPixmap(":/rare/imgs/rare/star_1.webp"))
        self.arti_head_area.setScaledContents(True)
        self.arti_head_area.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.arti_head_icon = QLabel(self.arti_area)
        self.arti_head_icon.setObjectName("arti_head_icon")
        self.arti_head_icon.setGeometry(QRect(25, 55, 160, 160))
        sizePolicy.setHeightForWidth(self.arti_head_icon.sizePolicy().hasHeightForWidth())
        self.arti_head_icon.setSizePolicy(sizePolicy)
        self.arti_head_icon.setMinimumSize(QSize(160, 160))
        self.arti_head_icon.setMaximumSize(QSize(160, 160))
        self.arti_head_icon.setPixmap(QPixmap(":/arti/imgs/arti/main/main.webp"))
        self.arti_head_icon.setScaledContents(True)
        self.arti_head_icon.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.arti_head_icon.setMargin(1)
        self.arti_dist = QComboBox(self.arti_area)
        self.arti_dist.setObjectName("arti_dist")
        self.arti_dist.setGeometry(QRect(5, 5, 200, 25))
        sizePolicy.setHeightForWidth(self.arti_dist.sizePolicy().hasHeightForWidth())
        self.arti_dist.setSizePolicy(sizePolicy)
        self.arti_dist.setMinimumSize(QSize(200, 25))
        self.arti_dist.setMaximumSize(QSize(200, 25))
        self.arti_dist.setStyleSheet("font: 10pt \"IBM Plex Sans\";")
        self.arti_back_area = QFrame(scan)
        self.arti_back_area.setObjectName("arti_back_area")
        self.arti_back_area.setGeometry(QRect(215, 35, 40, 40))
        sizePolicy.setHeightForWidth(self.arti_back_area.sizePolicy().hasHeightForWidth())
        self.arti_back_area.setSizePolicy(sizePolicy)
        self.arti_back_area.setMinimumSize(QSize(40, 40))
        self.arti_back_area.setMaximumSize(QSize(40, 40))
        self.arti_back_area.setStyleSheet("#arti_back_area {border-top-right-radius: 5px; border-bottom-right-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_back_area.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_back_area.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_back_icon = QLabel(self.arti_back_area)
        self.arti_back_icon.setObjectName("arti_back_icon")
        self.arti_back_icon.setGeometry(QRect(5, 5, 30, 30))
        sizePolicy.setHeightForWidth(self.arti_back_icon.sizePolicy().hasHeightForWidth())
        self.arti_back_icon.setSizePolicy(sizePolicy)
        self.arti_back_icon.setMinimumSize(QSize(30, 30))
        self.arti_back_icon.setMaximumSize(QSize(30, 30))
        self.arti_back_icon.setPixmap(QPixmap(":/arti/imgs/arti/main/main.webp"))
        self.arti_back_icon.setScaledContents(True)
        self.arti_back_icon.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.arti_back_icon.setMargin(1)
        self.arti_cnvs = QFrame(scan)
        self.arti_cnvs.setObjectName("arti_cnvs")
        self.arti_cnvs.setGeometry(QRect(260, 35, 875, 495))
        sizePolicy.setHeightForWidth(self.arti_cnvs.sizePolicy().hasHeightForWidth())
        self.arti_cnvs.setSizePolicy(sizePolicy)
        self.arti_cnvs.setMinimumSize(QSize(875, 495))
        self.arti_cnvs.setMaximumSize(QSize(875, 495))
        self.arti_cnvs.setStyleSheet("#arti_cnvs  {border-top-left-radius: 5px; border-bottom-left-radius: 5px; border-bottom-right-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_cnvs.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_cnvs.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_shot = QLabel(self.arti_cnvs)
        self.arti_shot.setObjectName("arti_shot")
        self.arti_shot.setGeometry(QRect(5, 5, 865, 485))
        sizePolicy.setHeightForWidth(self.arti_shot.sizePolicy().hasHeightForWidth())
        self.arti_shot.setSizePolicy(sizePolicy)
        self.arti_shot.setMinimumSize(QSize(865, 485))
        self.arti_shot.setMaximumSize(QSize(865, 485))
        self.arti_shot.setStyleSheet("#arti_shot {font: 10pt \"IBM Plex Sans\"; background-color: rgba(128, 128, 128, 128);}")
        self.arti_shot.setScaledContents(True)
        self.arti_shot.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.arti_cnvs_area = QFrame(scan)
        self.arti_cnvs_area.setObjectName("arti_cnvs_area")
        self.arti_cnvs_area.setGeometry(QRect(1135, 35, 40, 40))
        sizePolicy.setHeightForWidth(self.arti_cnvs_area.sizePolicy().hasHeightForWidth())
        self.arti_cnvs_area.setSizePolicy(sizePolicy)
        self.arti_cnvs_area.setMinimumSize(QSize(40, 40))
        self.arti_cnvs_area.setMaximumSize(QSize(40, 40))
        self.arti_cnvs_area.setStyleSheet("#arti_cnvs_area {border-top-right-radius: 5px; border-bottom-right-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_cnvs_area.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_cnvs_area.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_cnvs_icon = QLabel(self.arti_cnvs_area)
        self.arti_cnvs_icon.setObjectName("arti_cnvs_icon")
        self.arti_cnvs_icon.setGeometry(QRect(5, 5, 30, 30))
        sizePolicy.setHeightForWidth(self.arti_cnvs_icon.sizePolicy().hasHeightForWidth())
        self.arti_cnvs_icon.setSizePolicy(sizePolicy)
        self.arti_cnvs_icon.setMinimumSize(QSize(30, 30))
        self.arti_cnvs_icon.setMaximumSize(QSize(30, 30))
        self.arti_cnvs_icon.setPixmap(QPixmap(":/arti/imgs/arti/main/main.webp"))
        self.arti_cnvs_icon.setScaledContents(True)
        self.arti_cnvs_icon.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.arti_cnvs_icon.setMargin(1)
        self.arti_cnvs_head = QFrame(scan)
        self.arti_cnvs_head.setObjectName("arti_cnvs_head")
        self.arti_cnvs_head.setGeometry(QRect(1140, 435, 35, 95))
        sizePolicy.setHeightForWidth(self.arti_cnvs_head.sizePolicy().hasHeightForWidth())
        self.arti_cnvs_head.setSizePolicy(sizePolicy)
        self.arti_cnvs_head.setMinimumSize(QSize(35, 95))
        self.arti_cnvs_head.setMaximumSize(QSize(35, 95))
        self.arti_cnvs_head.setStyleSheet("#arti_cnvs_head {border-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_cnvs_head.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_cnvs_head.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_cnvs_load = QPushButton(self.arti_cnvs_head)
        self.arti_cnvs_load.setObjectName("arti_cnvs_load")
        self.arti_cnvs_load.setGeometry(QRect(5, 5, 25, 25))
        sizePolicy.setHeightForWidth(self.arti_cnvs_load.sizePolicy().hasHeightForWidth())
        self.arti_cnvs_load.setSizePolicy(sizePolicy)
        self.arti_cnvs_load.setMinimumSize(QSize(25, 25))
        self.arti_cnvs_load.setMaximumSize(QSize(25, 25))
        self.arti_cnvs_load.setStyleSheet("#arti_cnvs_load {font: 87 10pt \"Font Awesome 6 Free Solid\";}")
        self.arti_cnvs_conf = QPushButton(self.arti_cnvs_head)
        self.arti_cnvs_conf.setObjectName("arti_cnvs_conf")
        self.arti_cnvs_conf.setGeometry(QRect(5, 35, 25, 25))
        sizePolicy.setHeightForWidth(self.arti_cnvs_conf.sizePolicy().hasHeightForWidth())
        self.arti_cnvs_conf.setSizePolicy(sizePolicy)
        self.arti_cnvs_conf.setMinimumSize(QSize(25, 25))
        self.arti_cnvs_conf.setMaximumSize(QSize(25, 25))
        self.arti_cnvs_conf.setStyleSheet("#arti_cnvs_conf {font: 87 10pt \"Font Awesome 6 Free Solid\";}")
        self.arti_cnvs_wipe = QPushButton(self.arti_cnvs_head)
        self.arti_cnvs_wipe.setObjectName("arti_cnvs_wipe")
        self.arti_cnvs_wipe.setGeometry(QRect(5, 65, 25, 25))
        sizePolicy.setHeightForWidth(self.arti_cnvs_wipe.sizePolicy().hasHeightForWidth())
        self.arti_cnvs_wipe.setSizePolicy(sizePolicy)
        self.arti_cnvs_wipe.setMinimumSize(QSize(25, 25))
        self.arti_cnvs_wipe.setMaximumSize(QSize(25, 25))
        self.arti_cnvs_wipe.setStyleSheet("#arti_cnvs_wipe {font: 87 10pt \"Font Awesome 6 Free Solid\";}")
        self.arti_back_head = QFrame(scan)
        self.arti_back_head.setObjectName("arti_back_head")
        self.arti_back_head.setGeometry(QRect(220, 465, 35, 65))
        sizePolicy.setHeightForWidth(self.arti_back_head.sizePolicy().hasHeightForWidth())
        self.arti_back_head.setSizePolicy(sizePolicy)
        self.arti_back_head.setMinimumSize(QSize(35, 65))
        self.arti_back_head.setMaximumSize(QSize(35, 65))
        self.arti_back_head.setStyleSheet("#arti_back_head {border-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_back_head.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_back_head.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_back_done = QPushButton(self.arti_back_head)
        self.arti_back_done.setObjectName("arti_back_done")
        self.arti_back_done.setGeometry(QRect(5, 5, 25, 25))
        sizePolicy.setHeightForWidth(self.arti_back_done.sizePolicy().hasHeightForWidth())
        self.arti_back_done.setSizePolicy(sizePolicy)
        self.arti_back_done.setMinimumSize(QSize(25, 25))
        self.arti_back_done.setMaximumSize(QSize(25, 25))
        self.arti_back_done.setStyleSheet("#arti_back_done {font: 87 10pt \"Font Awesome 6 Free Solid\";}")
        self.arti_back_wipe = QPushButton(self.arti_back_head)
        self.arti_back_wipe.setObjectName("arti_back_wipe")
        self.arti_back_wipe.setGeometry(QRect(5, 35, 25, 25))
        sizePolicy.setHeightForWidth(self.arti_back_wipe.sizePolicy().hasHeightForWidth())
        self.arti_back_wipe.setSizePolicy(sizePolicy)
        self.arti_back_wipe.setMinimumSize(QSize(25, 25))
        self.arti_back_wipe.setMaximumSize(QSize(25, 25))
        self.arti_back_wipe.setStyleSheet("#arti_back_wipe {font: 87 10pt \"Font Awesome 6 Free Solid\";}")
        self.arti_head = QFrame(scan)
        self.arti_head.setObjectName("arti_head")
        self.arti_head.setGeometry(QRect(5, 5, 1170, 25))
        sizePolicy.setHeightForWidth(self.arti_head.sizePolicy().hasHeightForWidth())
        self.arti_head.setSizePolicy(sizePolicy)
        self.arti_head.setMinimumSize(QSize(1170, 25))
        self.arti_head.setMaximumSize(QSize(1170, 25))
        self.arti_head.setStyleSheet("#arti_head  {border-radius: 5px; background-color: rgba(128, 128, 128, 64);}")
        self.arti_head.setFrameShape(QFrame.Shape.StyledPanel)
        self.arti_head.setFrameShadow(QFrame.Shadow.Raised)
        self.arti_text = QLabel(self.arti_head)
        self.arti_text.setObjectName("arti_text")
        self.arti_text.setGeometry(QRect(5, 5, 1160, 15))
        sizePolicy.setHeightForWidth(self.arti_text.sizePolicy().hasHeightForWidth())
        self.arti_text.setSizePolicy(sizePolicy)
        self.arti_text.setMinimumSize(QSize(1160, 15))
        self.arti_text.setMaximumSize(QSize(1160, 15))
        self.arti_text.setStyleSheet("font: 10pt \"IBM Plex Sans\";")

        self.retranslateUi(scan)

        QMetaObject.connectSlotsByName(scan)
    # setupUi

    def retranslateUi(self, scan):
        scan.setWindowTitle(QCoreApplication.translate("scan", "Dialog", None))
        self.arti_type_name.setText(QCoreApplication.translate("scan", "UNASSIGNED", None))
        self.arti_data_b.setPlaceholderText(QCoreApplication.translate("scan", "Data", None))
        self.arti_data_a.setPlaceholderText(QCoreApplication.translate("scan", "Data", None))
        self.arti_data_c.setPlaceholderText(QCoreApplication.translate("scan", "Data", None))
        self.arti_data_main.setPlaceholderText(QCoreApplication.translate("scan", "Data", None))
        self.arti_data_d.setPlaceholderText(QCoreApplication.translate("scan", "Data", None))
        self.arti_head_area.setText("")
        self.arti_head_icon.setText("")
        self.arti_back_icon.setText("")
        self.arti_shot.setText(QCoreApplication.translate("scan", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">YOUR ARTIFACT SCREENSHOT WILL SHOW UP HERE</span></p><p align=\"center\">INSERT AN ARTIFACT SCREENSHOT HERE BY EITHER PRESSING<span style=\" font-weight:700;\"> CTRL + V</span> OR USING <span style=\" font-weight:700;\">DRAG AND DROP</span></p></body></html>", None))
        self.arti_cnvs_icon.setText("")
#if QT_CONFIG(tooltip)
        self.arti_cnvs_load.setToolTip(QCoreApplication.translate("scan", "Load", None))
#endif // QT_CONFIG(tooltip)
        self.arti_cnvs_load.setText(QCoreApplication.translate("scan", "folder-open", None))
#if QT_CONFIG(tooltip)
        self.arti_cnvs_conf.setToolTip(QCoreApplication.translate("scan", "Locate", None))
#endif // QT_CONFIG(tooltip)
        self.arti_cnvs_conf.setText(QCoreApplication.translate("scan", "gear", None))
#if QT_CONFIG(tooltip)
        self.arti_cnvs_wipe.setToolTip(QCoreApplication.translate("scan", "Wipe", None))
#endif // QT_CONFIG(tooltip)
        self.arti_cnvs_wipe.setText(QCoreApplication.translate("scan", "trash", None))
#if QT_CONFIG(tooltip)
        self.arti_back_done.setToolTip(QCoreApplication.translate("scan", "Import", None))
#endif // QT_CONFIG(tooltip)
        self.arti_back_done.setText(QCoreApplication.translate("scan", "circle-check", None))
#if QT_CONFIG(tooltip)
        self.arti_back_wipe.setToolTip(QCoreApplication.translate("scan", "Wipe", None))
#endif // QT_CONFIG(tooltip)
        self.arti_back_wipe.setText(QCoreApplication.translate("scan", "trash", None))
        self.arti_text.setText(QCoreApplication.translate("scan", "Browse your local storage to load a high quality screenshot of your artifact and the statistics will automatically be computed from there.", None))
    # retranslateUi

