__test_arti__ = {
    "fwol": {
        "rare": "Star 5",
        "levl": "Level 20",
        "main": "HP",
        "type": "Emblem of Severed Fate",
        "name": "Magnificent Tsuba",
        "stat": {
            "a": {"name": "Crit Rate", "data": 12.0},
            "b": {"name": "Crit DMG", "data": 34.0},
            "c": {"name": "Elemental Mastery", "data": 56.0},
            "d": {"name": "Energy Recharge", "data": 78.0},
        },
    },
    "pmod": {
        "rare": "Star 5",
        "levl": "Level 20",
        "main": "ATK",
        "type": "Emblem of Severed Fate",
        "name": "Sundered Feather",
        "stat": {
            "a": {"name": "DEF", "data": 12.0},
            "b": {"name": "DEF %", "data": 34.0},
            "c": {"name": "HP", "data": 56.0},
            "d": {"name": "HP %", "data": 78.0},
        },
    },
    "sdoe": {
        "rare": "Star 5",
        "levl": "Level 20",
        "main": "Elemental Mastery",
        "type": "Shimenawa's Reminiscence",
        "name": "Morning Dew's Moment",
        "stat": {
            "a": {"name": "ATK", "data": 12.0},
            "b": {"name": "ATK %", "data": 34.0},
            "c": {"name": "Crit Rate", "data": 56.0},
            "d": {"name": "Crit DMG", "data": 78.0},
        },
    },
    "gboe": {
        "rare": "Star 5",
        "levl": "Level 20",
        "main": "Physical DMG Bonus",
        "type": "Shimenawa's Reminiscence",
        "name": "Hopeful Heart",
        "stat": {
            "a": {"name": "Elemental Mastery", "data": 12.0},
            "b": {"name": "Energy Recharge", "data": 34.0},
            "c": {"name": "HP %", "data": 56.0},
            "d": {"name": "HP", "data": 78.0},
        },
    },
    "ccol": {
        "rare": "Star 5",
        "levl": "Level 20",
        "main": "Healing Bonus",
        "type": "Noblesse Oblige",
        "name": "Royal Masque",
        "stat": {
            "a": {"name": "ATK", "data": 12.0},
            "b": {"name": "ATK %", "data": 34.0},
            "c": {"name": "Crit Rate", "data": 56.0},
            "d": {"name": "Crit DMG", "data": 78.0},
        },
    },
}
