---
name: Compiling the nightly project executable binary for GNU/Linux OSes

on:
  schedule:
    - cron: 0 0 * * *

jobs:

  ci-make-gnul:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:

      - name: Checkout the codebase in a local working directory
        uses: actions/checkout@v6

      - name: Establish a functioning Python development environment
        uses: actions/setup-python@v6
        with:
          python-version: 3.13 || 3.14

      - name: Evaluate the revision identifier for versioning
        id: hash
        shell: bash
        run: echo "code=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Update the interstitial identifier for versioning
        run: sed --in-place "s/^version = \"\(.*\)\"/version = \"\1+${{ steps.hash.outputs.code }}\"/" pyproject.toml

      - name: Install the project's required runtime dependencies
        run: pip install .

      - name: Build the executable binary for the specified platform
        uses: Nuitka/Nuitka-Action@main
        with:
          script-name: gi_loadouts/main.py
          mode: onefile
          enable-plugins: pyside6
          output-dir: dist
          output-file: gi-loadouts-${{ steps.hash.outputs.code }}
          linux-icon: assets/icon/icon.ico

      - name: Upload the compiled binaries to the GitHub Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: gi-loadouts.gnul
          path: dist/gi-loadouts-*
          retention-days: 2
          compression-level: 9
          overwrite: true
