---
name: Building the project binary for Microsoft Windows

on:
  schedule:
    - cron: 0 0 * * *

jobs:

  ci-make-mswn:

    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:

      - name: Checkout the codebase in local working directory
        uses: actions/checkout@v5

      - name: Setup a functioning local Python 3 installation
        uses: actions/setup-python@v6
        with:
          python-version: 3.12 || 3.13

      - name: Install the base dependencies of the project
        run: python3 -m pip install --upgrade poetry pyinstaller

      - name: Disable using virtual environments with Poetry
        run: poetry config virtualenvs.create false

      - name: Ignore warnings about dubious repository ownership
        run: git config --global --add safe.directory .

      - name: Update the interstitial versioning identifier
        run: (Get-Content -Raw pyproject.toml) -replace 'version\s*=\s*"([^"]*)"', ('version = "$1+' + (git rev-parse --short=8 HEAD) + '"') | Set-Content pyproject.toml

      - name: Install the runtime dependencies of the project
        run: python3 -m poetry install

      - name: Build the project binary for "Loadouts for Genshin Impact"
        run: pyinstaller gi_loadouts/main.py --clean --onefile --name gi-loadouts-$("$env:GITHUB_HASH".SubString(0, 8)) --windowed --icon assets/icon/icon.ico
        env:
          GITHUB_HASH: ${{ github.sha }}

      - name: Upload the project binaries for "Loadouts for Genshin Impact"
        uses: actions/upload-artifact@v5
        with:
          name: gi-loadouts.mswn
          path: dist/gi-loadouts-*.exe
          retention-days: 2
          compression-level: 9
          overwrite: true
